version: 2.1
jobs:
  build:
    docker:
    - image: circleci/openjdk:11-jdk
    # specify the version you desire here
   # - image: cimg/mysql:8.0
      #specify system properties
      environment:
        DB_ROOT_USER: $DB_USERNAME
        DB_DRIVER: com.mysql.cj.jdbc.Driver
        DB_PASS: $DB_PASSWORD
        MEMBER_DB_URL: $DB_URL
      
        TZ: Europe/Prague
      # Specify our database service here
      # CircleCI maintains a library of pre-built images
    #- image: circleci/mysql:5.7
    #  environment:
    #    MYSQL_ROOT_PASSWORD: password
    #working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "backend/build.gradle" }}
            # fallback to using the latest cache if no exact match is found

      - run: 
          name: chmod permissions
          command: sudo chmod +x ./backend/gradlew && ./backend/gradlew compileDebug --stacktrace
            # sudo chmod +x ./backend/gradlew
          

      - save_cache:
          paths:
            - ~/backend/.gradle
          key: v1-dependencies-{{ checksum "backend/build.gradle" }}


      # run checkstyle
      #- run: gradle checkstyleMain
      #- run: gradle checkstyleTest
      #- store_artifacts:
      #    path: build/reports/checkstyle

      # run tests!
      - run: ./backend/gradlew test
      - store_artifacts:
          path: build/reports/jacoco/test
